int_var=10
float_var=10.5
complex_var=10+8j
string_var="Hello"
list_var=[1,2,3,4]
tuple_var=(10,20,30)
range_var=range(5)
dict_var={"name":"Rosh","Age":19}
set_var={1,2,3}
frozenset_var=frozenset({4,5,6})
bool_var=True
none_var=None
bytes_var=bytes(5)
bytearray_var=bytearray(7)
print(f"{int_var}:{type(int_var)}")
print(f"{float_var}:{type(float_var)}")
print(f"{complex_var}:{type(complex_var)}")
print(f"{string_var}:{type(string_var)}")
print(f"{list_var}:{type(list_var)}")
print(f"{tuple_var}:{type(tuple_var)}")
print(f"{range_var}:{type(range_var)}")
print(f"{dict_var}:{type(dict_var)}")
print(f"{set_var}:{type(set_var)}")
print(f"{frozenset_var}:{type(frozenset_var)}")
print(f"{bool_var}:{type(bool_var)}")
print(f"{none_var}:{type(none_var)}")
print(f"{bytes_var}:{type(bytes_var)}")
print(f"{bytearray_var}:{type(bytearray_var)}")
