principle=float(input("Amount : "))
interest=float(input("Interest Rate : "))
year=int(input("Number of Years : "))
print(f"Interest Amount = {(principle*interest*year)/100}")
print(f"Total Amount = {principle+((principle*interest*year)/100)}")
